languages:
  - "fr_FR"

scoreboards:
  refresh-time: 15 # (ticks)
  # basic - Le scoreboard par défaut
  # prestige - Le scoreboard premium
  # deathmatch - Le scoreboard lorsqu'il y a l'event deathmatch en cours
  # raffle - Le scoreboard lorsqu'il y a l'event raffle en cours
  # spire - Le scoreboard lorsqu'il y a l'event spire en cours
  basic: # {level}, {xp}, {or}, {credits}, {etoiles}, {votecoins}, {online}
    title: "§l§dLEGACY"
    lines:
      - " "
      - "§fNiveau§7: {level}"
      - "§fEXP restant§7: §b{xp}"
      - "  "
      - "§fOr§7: §6{or}"
      - "§fCrédits§7: §a{credits}"
      - "§fÉtoiles§7: §e{etoiles}"
      - "§fVoteCoins§7: §9{votecoins}"
      - "   "
      - "§fServeur§7: §c{online}"
      - "    "
      - "legacymc.eu"
  prestige: # {prestige}, {level}, {xp}, {or}, {credits}, {etoiles}, {votecoins}, {online}
    title: "§l§dLEGACY"
    lines:
      - " "
      - "§fPrestige§7: §e{prestige}"
      - "§fNiveau§7: {level}"
      - "§fEXP restant§7: §b{xp}"
      - "  "
      - "§fOr§7: §6{or}"
      - "§fCrédits§7: §a{credits}"
      - "§fÉtoiles§7: §e{etoiles}"
      - "§fVoteCoins§7: §9{votecoins}"
      - "   "
      - "§fServeur§7: §c{online}"
      - "     "
      - "legacymc.eu"
  deathmatch: # {timeleft}, {kills}, {position}, {kills_blue}, {kills_red}, {prestige}, {level}, {xp}, {online}
    title: ""
    lines:
      - ""
      - ""
  raffle: # {timeleft}, {tickets}, {position}, {cagnotte}, {prestige}, {level}, {xp}, {online}
    title: ""
    lines:
      - ""
      - ""
  spire: # {timeleft}, {stage}, {kills}, {prestige}, {level}, {xp}, {online}
    title: ""
    lines:
      - ""
      - ""

grades:
  Admin:
    chat: "§a{player} §f-> §2{chat}"
    nametag: ""
    scoretag: ""
    permissions: []

commands:
  ban:
    permission: "legacy.commands.ban"
    usage: "/ban <player> <time> <ip> <reason>"
    description: "Bannir un joueur"
    aliases: []
  unban:
    permission: "legacy.commands.unban"
    usage: "/unban <player>"
    description: "Débannir un joueur"
    aliases: []
  kick:
    permission: "legacy.commands.kick"
    usage: "/kick <player>"
    description: "Expulser un joueur"
    aliases: []