prefixes:
  1: "§5[§dLegacy§r§5] §r"
  2: "§5[§d§l!!!§r§5] §r"
  3: "§5[§d§l!§r§5] §r"

languages:
  - "fr_FR"

knockback:
  horizontal: 0.40
  vertical: 0.40
  attack_cooldown: 10

scoreboards:
  refresh-time: 15 # (ticks)
  # basic - Le scoreboard par défaut
  # prestige - Le scoreboard premium
  # deathmatch - Le scoreboard lorsqu'il y a l'event deathmatch en cours
  # raffle - Le scoreboard lorsqu'il y a l'event raffle en cours
  # spire - Le scoreboard lorsqu'il y a l'event spire en cours
  basic: # {level}, {xp}, {or}, {credits}, {etoiles}, {votecoins}, {online}
    title: "§l§dLEGACY"
    lines:
      - " "
      - "§fNiveau§7: {level}"
      - "§fEXP restant§7: §b{xp}"
      - "  "
      - "§fOr§7: §6{or}"
      - "§fCrédits§7: §a{credits}"
      - "§fÉtoiles§7: §e{etoiles}"
      - "§fVoteCoins§7: §9{votecoins}"
      - "   "
      - "§fServeur§7: §c{online}"
      - "    "
      - "legacymc.eu"
  prestige: # {prestige}, {level}, {xp}, {or}, {credits}, {etoiles}, {votecoins}, {online}
    title: "§l§dLEGACY"
    lines:
      - " "
      - "§fPrestige§7: §e{prestige}"
      - "§fNiveau§7: {level}"
      - "§fEXP restant§7: §b{xp}"
      - "  "
      - "§fOr§7: §6{or}"
      - "§fCrédits§7: §a{credits}"
      - "§fÉtoiles§7: §e{etoiles}"
      - "§fVoteCoins§7: §9{votecoins}"
      - "   "
      - "§fServeur§7: §c{online}"
      - "     "
      - "legacymc.eu"
  deathmatch: # {timeleft}, {kills}, {position}, {kills_blue}, {kills_red}, {prestige}, {level}, {xp}, {online}
    title: ""
    lines:
      - ""
      - ""
  raffle: # {timeleft}, {tickets}, {position}, {cagnotte}, {prestige}, {level}, {xp}, {online}
    title: ""
    lines:
      - ""
      - ""
  spire: # {timeleft}, {stage}, {kills}, {prestige}, {level}, {xp}, {online}
    title: ""
    lines:
      - ""
      - ""

ranks:
  Joueur:
    chat: "§7{player} §l§7» §r§7{chat}"
    nametag: "§7{player}"
    scoretag: ""
    permissions: []
  Plus:
    chat: "§8[§a+§8] §a{player} §l§8» §r§f{chat}"
    nametag: "§a{player}"
    scoretag: ""
    permissions: []
  Star:
    chat: "§8[§9Star§8] §9{player} §l§8» §r§f{chat}"
    nametag: "§9{player}"
    scoretag: ""
    permissions: []
  Booster:
    chat: "§8[§dBooster§8] §d{player} §l§8» §r§f{chat}"
    nametag: "§d{player}"
    scoretag: ""
    permissions: []
  YouTube:
    chat: "§8[§bYouTube§8] §b{player} §l§8» §r§f{chat}"
    nametag: "§b{player}"
    scoretag: ""
    permissions: []
  Famous:
    chat: "§8[§5Famous§8] §5{player} §l§8» §r§f{chat}"
    nametag: "§5{player}"
    scoretag: ""
    permissions: []
  Guide:
    chat: "§8[§2§lGuide§r§8] §2{player} §l§8» §r§2{chat}"
    nametag: "§2§l{player}"
    scoretag: ""
    permissions: []
  Modo:
    chat: "§8[§e§lModo§r§8] §e{player} §l§8» §r§e{chat}"
    nametag: "§e§l{player}"
    scoretag: ""
    permissions: []
  SuperModo:
    chat: "§8[§6§lSuperModo§r§8] §6{player} §l§8» §r§6{chat}"
    nametag: "§6§l{player}"
    scoretag: ""
    permissions: []
  Développeur:
    chat: "§8[§c§lDéveloppeur§r§8] §c{player} §l§8» §r§c{chat}"
    nametag: "§c§l{player}"
    scoretag: ""
    permissions: []
  Responsable:
    chat: "§8[§c§lResponsable§r§8] §c{player} §l§8» §r§c{chat}"
    nametag: "§c§l{player}"
    scoretag: ""
    permissions: []
  Admin:
    chat: "§8[§4§lAdmin§r§8] §4{player} §l§8» §r§4{chat}"
    nametag: "§l§4{player}"
    scoretag: ""
    permissions: []

commands:
  # <> = obligatoire
  # [] = optionnel
  ban:
    permission: "legacy.commands.ban"
    usage: "§fVous devez faire §d/ban <nom du joueur> <temps> [ip: [oui/non]] [raison] §fpour bannir un joueur."
    description: "Bannir un joueur"
    aliases: []
  unban:
    permission: "legacy.commands.unban"
    usage: "§fVous devez faire §d/unban <nom du joueur> §fpour débannir un joueur."
    description: "Débannir un joueur"
    aliases: []
  kick:
    permission: "legacy.commands.kick"
    usage: "§fVous devez faire §d/kick <nom du joueur> §fpour expulser un joueur."
    description: "Expulser un joueur"
    aliases: []
  setrank:
    permission: "legacy.commands.setrank"
    usage: "§fVous devez faire §d/setrank <nom du joueur> <grade> §fpour mettre un grade à un joueur."
    description: "Mettre un grade à un joueur"
    aliases: []
  listrank:
    permission: "legacy.commands.listrank"
    usage: "§fVous devez faire §d/listrank §fpour voir la liste des grades."
    description: "Voir la liste des ranks"
    aliases: []
  banlist:
    permission: "legacy.commands.banlist"
    usage: "§fVous devez faire §d/banlist §fpour voir la liste des joueurs bannis."
    description: "Voir la liste des joueurs bannis"
    aliases: []
  gamemode:
    permission: "legacy.commands.gamemode"
    usage: "§fVous devez faire §d/gamemode <mode> [nom du joueur] §fpour changer le mode de jeu d'un joueur."
    description: "Définir le gamemode d'un joueur"
    aliases:
      - gm
  say:
    permission: "legacy.commands.say"
    usage: "§fVous devez faire §d/say <message> §fpour faire une annonce."
    description: "Écrire une annonce"
    aliases:
      - s
      - sayall
  globalmute:
    permission: "legacy.commands.globalmute"
    usage: "§fVous devez faire §d/globalmute [mode: [true/false]] §fpour mute tous les joueurs."
    description: "Mute tous les joueurs"
    aliases:
      - muteall
  tpr:
    permission: "legacy.commands.tpr"
    usage: "§fVous devez faire §d/tpr §fpour vous téléporter aléatoirement à un joueur du serveur."
    description: "Se téléporter aléatoirement à un joueur du serveur"
    aliases:
      - randomtp
  tp:
    permission: "legacy.commands.tp"
    usage: "§fVous devez faire §d/tp <player1> [player2]"
    description: "Se téléporter à un joueur spécifique"
    aliases:
      - teleport
  knockback:
    permission: "legacy.commands.knockback"
    usage: "§fVous devez faire §d/knockback <x> <y> <force> [vertical-limit] (attack-cooldown)"
    description: "Changer le knockback du serveur"
    aliases:
      - kb
  nightvision:
    permission: "legacy.commands.nightvision"
    usage: "§fVous devez faire §d/nightvision §fpour activer ou désactiver la vision nocturne."
    description: "Activer la vision nocturne"
    aliases:
      - nv
  ping:
    permission: "legacy.commands.ping"
    usage: "§fVous devez faire §d/ping §fpour voir votre ping."
    description: "Voir votre ping ou d'un joueur"
    aliases:

items:
  nemo:
    horizontal: 2
    vertical: 0.50

cooldowns:
  1002: 15
