<?php

namespace Legacy\ThePit\Items\List;

use pocketmine\block\Block;
use pocketmine\item\Item;
use pocketmine\item\ItemIdentifier;
use pocketmine\item\ItemUseResult;
use pocketmine\math\Vector3;
use pocketmine\player\Player;

final class Flap extends Item
{
    public function __construct(ItemIdentifier $identifier, string $name = "Flap")
    {
        parent::__construct($identifier, $name);
    }

    public function onClickAir(Player $player, Vector3 $directionVector): ItemUseResult
    {
        return parent::onClickAir($player, $directionVector); // TODO: Change the autogenerated stub
    }

    public function onInteractBlock(Player $player, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector): ItemUseResult
    {
        return parent::onInteractBlock($player, $blockReplace, $blockClicked, $face, $clickVector); // TODO: Change the autogenerated stub
    }

    public function getMaxStackSize(): int
    {
        return 1;
    }
}